### ISSUE TITLE
use root-snapshot for all volumes

### ISSUE THREAD

**Issue by kaimee** [rancher/convoy#136] opened 2016-07-05 08:11 UTC
Currently (0.4.3) devicemapper can't be used with anonymous volumes easily:

docker run --rm --volume-driver convoy mysql
docker: Error response from daemon: no such file or directory.

Reason: the anonymous volume that was created is not empty but contains "lost&found" as pointed out in this issue https://github.com/rancher/convoy/issues/104

This could be fixed by deleting l&f after formatting operation.

However wouldn't it be even more efficient (faster) to create a new volume by snapshotting an already formatted "root" volume? (I think that's what docker dm does)
It may be more tricky to provide an option for individually sizing the volume but that may not matter so much in large standardized deployments.

best regards

**Comment by yasker** [comment] 2016-08-30 22:19
I don't think we will do root-snapshot for every volume, not worth the effect if remove `lost and found` easily worked. 

Mark as duplicate of #104 , and move discussion to there

**Closed by yasker** 2016-08-30 22:19 UTC
