### ISSUE TITLE
"Error": "BUG: glusterfs.GlusterFSVolume doesn't have required field Name"

### ISSUE THREAD

**Issue by ndarilek** [rancher/convoy#132] opened 2016-06-23 02:43 UTC
Wow, this is confusing. I just filed this issue against the community catalog because I thought the glusterfs code was maintained outside of this repository, by someone in the community.

I'm hitting various issues that may be fixed in newer Convoy drivers, mainly around removing volumes with `docker volume rm`. Seeing that the community Gluster catalog used v0.3 of this repository, I tried upgrading to V0.7 to see what would happen. I got the error in this issue's title, and the log included below.

Any chance the Gluster driver will be updated to work in V0.7? I can't `docker volume rm` volumes because I suspect 0.3 isn't compatible with Docker 1.10.3.

```
Waiting for metadata
time="2016-06-23T02:00:14Z" level=info msg="Execing [/usr/bin/nsenter --mount=/proc/27301/ns/mnt -F -- /var/lib/docker/aufs/mnt/fcce70de21b33415a276d79b1bf8dd7ac1637e5e543cc1fcf77b37142c95726c/var/lib/rancher/convoy-agent/share-mnt --stage2 /var/lib/rancher/convoy/convoy-gluster-acf30ea9-00c1-46de-b7cc-fb2f0c31740f -- /launch volume-agent-glusterfs-internal]" 
Waiting for metadata
Registering convoy socket at /var/run/convoy-convoy-gluster.sock
time="2016-06-23T02:00:15Z" level=info msg="Listening for health checks on 0.0.0.0:10241/healthcheck" 
time="2016-06-23T02:00:15Z" level=info msg="Got: root /var/lib/rancher/convoy/convoy-gluster-acf30ea9-00c1-46de-b7cc-fb2f0c31740f" 
time="2016-06-23T02:00:15Z" level=info msg="Got: drivers [glusterfs]" 
time="2016-06-23T02:00:15Z" level=info msg="Got: driver-opts [glusterfs.defaultvolumepool=my_vol2 glusterfs.servers=glusterfs]" 
time="2016-06-23T02:00:15Z" level=info msg="Launching convoy with args: [--socket=/host/var/run/convoy-convoy-gluster.sock daemon --root=/var/lib/rancher/convoy/convoy-gluster-acf30ea9-00c1-46de-b7cc-fb2f0c31740f --drivers=glusterfs --driver-opts=glusterfs.defaultvolumepool=my_vol2 --driver-opts=glusterfs.servers=glusterfs]" 
time="2016-06-23T02:00:15Z" level=debug msg="Creating config at /var/lib/rancher/convoy/convoy-gluster-acf30ea9-00c1-46de-b7cc-fb2f0c31740f" pkg=daemon 
time="2016-06-23T02:00:15Z" level=debug msg= driver=glusterfs driver_opts=map[glusterfs.defaultvolumepool:my_vol2 glusterfs.servers:glusterfs] event=init pkg=daemon reason=prepare root="/var/lib/rancher/convoy/convoy-gluster-acf30ea9-00c1-46de-b7cc-fb2f0c31740f" 
time="2016-06-23T02:00:15Z" level=debug msg="Cleaning up environment..." pkg=daemon 
time="2016-06-23T02:00:15Z" level=error msg="BUG: glusterfs.GlusterFSVolume doesn't have required field Name" 
{
    "Error": "BUG: glusterfs.GlusterFSVolume doesn't have required field Name"
}
time="2016-06-23T02:00:15Z" level=info msg="convoy exited with error: exit status 1" 
time="2016-06-23T02:00:15Z" level=info msg=Exiting. 
```

**Comment by mastertinner** [comment] 2016-06-23 16:00
Duplicate of #121

**Comment by fbrbovic** [comment] 2016-07-07 20:30
Any idea when is this going to be fixed ?

**Comment by mastertinner** [comment] 2016-07-07 20:59
I made a PR: #134
It should be merged soon.

**Comment by yasker** [comment] 2016-08-30 22:05
PR #134 merged. But we're pulling the support for glusterfs in the foreseeable future due to resource limitation. Sorry about that...

**Comment by janeczku** [comment] 2016-10-28 12:18
Duplicate of https://github.com/rancher/convoy/issues/121 which was fixed in https://github.com/rancher/convoy/commit/2053eec006728ad83765c270879f3fbb00de6e05

**Closed** 2016-10-31 23:15 UTC
Labels: bug, low priority
